# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('img', models.CharField(max_length=256)),
                ('desc', models.TextField(max_length=512)),
                ('link', models.URLField()),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
