# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='completed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
